In [2]:
import torch
torch.__version__

/Users/amyfan/Desktop/pytorch-walkthrough/.venv/lib/python3.11/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),


'2.1.1'

A. CREATING TENSORS

In [2]:
scalar = torch.tensor(7)
scalar

NameError: name 'torch' is not defined

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

B. RANDOM TENSORS

In [ ]:
random_tensor = torch.rand(size =(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.2454, 0.0383, 0.8800, 0.0406],
         [0.4663, 0.3115, 0.5555, 0.6224],
         [0.5897, 0.3508, 0.8363, 0.9127]]),
 torch.float32)

In [ ]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

C. ZEROS AND ONES

In [ ]:
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [ ]:
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

D. CREATING A RANGE AND TENSORS LIKE

In [ ]:
zero_to_ten_deprecated = torch.range(0, 10)

zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

<ipython-input-19-7c87c37a9f0f>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

E. TENSOR DATATYPES

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults None
                               requires_grad=False) # if True, operations performed on tensor are recorded
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

F. GETTING INFO FROM TENSORS

In [ ]:
# Create tensor
some_tensor = torch.rand(3, 4)

# Find some details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU


tensor([[0.8565, 0.9736, 0.3849, 0.9783],
        [0.1910, 0.6305, 0.1561, 0.8930],
        [0.1221, 0.2448, 0.1370, 0.1445]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


H. MANIPULATING TENSORS - TENSOR OPERATIONS

In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor # Tensors don't change unless reassigned

tensor([1, 2, 3])

In [ ]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [ ]:
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [ ]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [ ]:
tensor # original tensor still unchanged

tensor([1, 2, 3])

In [ ]:
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)      # element-wise multiplication

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


I. MATRIX MULTIPLICATION - IS ALL YOU NEED

In [ ]:
# element-wise
tensor * tensor

tensor([1, 4, 9])

In [ ]:
# Matrix multiplication (RECOMMENDED - FASTER)
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# also use the '@' symbol for matrix multiplication (NOT RECOMMENDED)
tensor @ tensor

tensor(14)

In [ ]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.37 ms, sys: 71 µs, total: 1.44 ms
Wall time: 2.18 ms


tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.05 ms, sys: 11 µs, total: 1.06 ms
Wall time: 3.39 ms


tensor(14)

I. MOST COMMON ERRORS - Shape Errors

In [ ]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: ignored

In [ ]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [ ]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [ ]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


J. FIND MIN, MAX, MEAN, SUM, ETC. - aggregation

In [3]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [5]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print (f"Mean: {x.mean()}") # will error, must be float
print(f"Mean: {x.type(torch.float32).mean()}")
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


In [7]:
# Can do the same with torch methods
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

K. POSITIONAL MIN/MAX

In [8]:
# Create a tensor

tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


K. CHANGE TENSOR DATATYPE

In [9]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [10]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [11]:
# Create a int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

# Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep as original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or horizontally (hstack)
* Squeeze - removes all `1` dimensions from tensor
* Unsqueeze - add a `1` dimension to a target tnesor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [21]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [22]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [23]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [24]:
# Changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:, 0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [27]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
print(x_stacked)
x_stacked = torch.stack([x, x, x, x], dim=1)
print(x_stacked)

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])


In [36]:
# torch.squeez() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [40]:
# torch.unsqueeze() - adds a dimension of 1 to a target tensor
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [46]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}") # [color_channels, height, width]
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [47]:
print(f"Previous original value: {x_original[0, 0, 0]}")
print(f"Previous permuted value: {x_permuted[0, 0, 0]}")

x_original[0, 0, 0] = 721818

print(f"New original value: {x_original[0, 0, 0]}")
print(f"New permuted value: {x_permuted[0, 0, 0]}")

Previous original value: 0.7307237386703491
Previous permuted value: 0.7307237386703491
New original value: 721818.0
New permuted value: 721818.0


### INDEXING (selecting data from tensors)
similar to indexing with NumPy.

In [1]:
# Create a tensor 
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

/Users/amyfan/Desktop/pytorch-walkthrough/.venv/lib/python3.11/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [2]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [4]:
# Let's index on the mdidle bracket (dim = 1)
print(x[0,0])
print(x[0][0])

tensor([1, 2, 3])
tensor([1, 2, 3])


In [7]:
# Let's index on the most inner bracket (last dimension)
x[0][2][2]

tensor(9)

In [8]:
# You can also use ":" to select all items in a given dimension
x[:,0]

tensor([[1, 2, 3]])

In [9]:
# Get all values of the 0th and 1st dimensions but only index 1 of 2nd dimension
print(x[:,:,1])

tensor([[2, 5]])
tensor([[2, 5, 8]])


In [10]:
# Get all values of the 0 dimnesion but only the 1 index value of the 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [11]:
# get index 0 of 0th dimension and 1st dimension but all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [14]:
#  Index on x to return 9
x[0,2,2]

# Index on x to return 3,6,9
x[0,:,2]

tensor([3, 6, 9])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> torch.Tensor.numpy()

In [1]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
# tensor = torch.from_numpy(array).type(torch.float32) # this would convert the tensor to float32
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [5]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [4]:
torch.arange(1.0, 8.0).dtype # default is float32

torch.float32

In [6]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor  # does not change tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [10]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor =  tensor.numpy()
tensor, numpy_tensor  # numpy dtype reflects pytorch dtype

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [12]:
# Change the tensor, what happens to the numpy array?
tensor = tensor + 1
tensor, numpy_tensor  # does not change numpy array

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavor" the randomness.

In [61]:
import torch

# Create 2 random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"First random tensor: \n{random_tensor_A}\n")
print(f"Second random tensor: \n{random_tensor_B}\n")
print(f"Are they equal? \n{random_tensor_A == random_tensor_B}\n")


First random tensor: 
tensor([[0.8535, 0.0765, 0.8591, 0.2651],
        [0.9674, 0.7205, 0.8644, 0.2256],
        [0.1597, 0.7503, 0.5221, 0.8955]])

Second random tensor: 
tensor([[0.4372, 0.6934, 0.9168, 0.3025],
        [0.3448, 0.6936, 0.9124, 0.5242],
        [0.2828, 0.8182, 0.8260, 0.3967]])

Are they equal? 
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])



In [63]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(f"First random tensor: \n{random_tensor_C}\n")
print(f"Second random tensor: \n{random_tensor_D}\n")
print(f"Are they equal? \n{random_tensor_C == random_tensor_D}\n")

First random tensor: 
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Second random tensor: 
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Are they equal? 
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])



##  Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything good

### 1. Getting a GPU

1. Easiest way to get access to a GPU? Google Colab (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, lots of options
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2,3 PyTorch + GPU drivers (CUDA) takes a bit of setting up, to do this, refer to PyTorch setup documentation

### 2. Get PyTorch to run on GPU

We will be using an accelerator (GPU that is CPU-integrated) on this computer.

'mps' is a GPU but it is not a dedicated GPU (so not as fast).

In [1]:
# Set the device type
from functions import get_device
import torch

get_device() # we use 'mps' which is an accelerator that speeds up CPU

'mps'

### 3. Putting tensors (and models) on the GPU

Which are faster.

In [12]:
# Create a tensor (default on CPU)
tensor = torch.tensor([1, 2, 3], device = 'cpu')

# Tensor not on GPU or mps accelerator
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [13]:
# Move tensor to GPU or mps accelerator (if available)
tensor_on_gpu = tensor.to(get_device()) # moves the tensor to the device
tensor_on_gpu, tensor_on_gpu.device # index is device number

(tensor([1, 2, 3], device='mps:0'), device(type='mps', index=0))

### 4. Moving tensors back to the CPU

* Some operations (e.g. NumPy) only work on the CPU

In [14]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert mps:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [15]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [16]:
tensor_on_gpu

tensor([1, 2, 3], device='mps:0')